# Generated by Django 4.1.1 on 2022-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
