# Generated by Django 4.1.1 on 2022-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
