# Generated by Django 4.1.1 on 2022-11-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_profile_photo'),
    ]

    operations = [
    ]
