# Generated by Django 4.1.1 on 2022-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221112_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(default='none', upload_to='profile_photos'),
            preserve_default=False,
        ),
    ]
