# Generated by Django 4.1.1 on 2022-11-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appuser_profile_photo'),
    ]

    operations = [
    ]
