# Generated by Django 4.1.1 on 2022-11-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221112_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_photo',
        ),
    ]
