# Generated by Django 4.1.1 on 2022-11-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_image_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
