# Generated by Django 4.1.1 on 2022-11-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_photo',
            field=models.ImageField(default='', upload_to='profile_photos'),
        ),
    ]
