# Generated by Django 4.1.1 on 2022-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appuser_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_photo',
            field=models.ImageField(upload_to='profile_photos'),
        ),
    ]
