# Generated by Django 4.1.1 on 2022-11-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_appuser_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
