# Generated by Django 4.1.1 on 2022-10-12 19:52

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media_files/pets_photos', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
