# Generated by Django 4.1.1 on 2022-10-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photolike_photocomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='to_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photolike',
            old_name='to_photo',
            new_name='photo',
        ),
    ]
