# Generated by Django 4.1.1 on 2022-10-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_rename_to_photo_photocomment_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photolike',
            name='photo',
        ),
        migrations.DeleteModel(
            name='PhotoComment',
        ),
        migrations.DeleteModel(
            name='PhotoLike',
        ),
    ]
