# Generated by Django 4.1.1 on 2022-11-04 01:50

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_remove_photolike_photo_delete_photocomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/pets_photos', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
