# Generated by Django 4.1.1 on 2022-11-04 02:16

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pets_photos', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
